// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUI3BA1Ft1b3_NzoxzZfMIonWaZNPXM-4',
    appId: '1:69909158713:web:3f37cf2271eaca00f766e8',
    messagingSenderId: '69909158713',
    projectId: 'ecommerce-ce67d',
    authDomain: 'ecommerce-ce67d.firebaseapp.com',
    storageBucket: 'ecommerce-ce67d.appspot.com',
    measurementId: 'G-CSP0WFHNY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz1JCoZpqV9KsWyoVJqNkTz_4NKnDllJc',
    appId: '1:69909158713:android:1dfea858f9e8dda9f766e8',
    messagingSenderId: '69909158713',
    projectId: 'ecommerce-ce67d',
    storageBucket: 'ecommerce-ce67d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-UPMVvg_R_3h_fu7rdEVKzU7Z76Aizyk',
    appId: '1:69909158713:ios:0655773ed2723b93f766e8',
    messagingSenderId: '69909158713',
    projectId: 'ecommerce-ce67d',
    storageBucket: 'ecommerce-ce67d.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-UPMVvg_R_3h_fu7rdEVKzU7Z76Aizyk',
    appId: '1:69909158713:ios:0655773ed2723b93f766e8',
    messagingSenderId: '69909158713',
    projectId: 'ecommerce-ce67d',
    storageBucket: 'ecommerce-ce67d.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUI3BA1Ft1b3_NzoxzZfMIonWaZNPXM-4',
    appId: '1:69909158713:web:141cdd2ff7db7810f766e8',
    messagingSenderId: '69909158713',
    projectId: 'ecommerce-ce67d',
    authDomain: 'ecommerce-ce67d.firebaseapp.com',
    storageBucket: 'ecommerce-ce67d.appspot.com',
    measurementId: 'G-CBCL5YZWXS',
  );
}
